### ISSUE TITLE
Rendering crashes if site is not allowed access to LocalStorage / cookies

### ISSUE THREAD

**Issue by ghost** [Spectralitree/pk-webs#1]
We tried to view an user's public profile page on <https://spectralitree.github.io/pk-webs/profile/{systemid}>. We have cookies and site storage disabled by default, and since the public profile page doesn't (shouldn't?) save any information anywhere, we thought it'd work without giving it storage permissions, but for some reason it doesn't
![h](https://user-images.githubusercontent.com/64013111/123345930-266b3b00-d525-11eb-9d00-7d10a58edbe8.png)

**Comment by Draconizations** [comment]
I'm assuming it doesn't work because of other preferences that are saved in localstorage, like the dark mode and other viewing preferences. we might look into this in the future though!
