### ISSUE TITLE
Cannot view system members if system list is private

### ISSUE THREAD

**Issue by ghost** [Spectralitree/pk-webs#2]
I am trying to view the profile of a public member in a system whose list is private. I get the following error:
> This system does not have a member with the ID 'jlppn', or the member's visibility is set to private.

Setting the member list to public and changing nothing else lets me view the member.

**Comment by Draconizations** [comment]
Hi, sorry for the late reply!

This is intentional and done out of privacy concerns. We might add a feature that just lets you look up members by just their ID in the future, but for now the only way to view a member is to make both the member list and member itself public.

**Comment by ghost** [comment]
Makes sense, no worries for the delay in replying.
